# Generated by Django 4.2.7 on 2023-12-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplemodel",
            name="numeric",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="simplemodel",
            name="truthy",
            field=models.BooleanField(default=True),
        ),
    ]
